### PR TITLE
fix(deps): ensure pino import resolves at runtime

### LINKED ISSUE #1634: (0 , _walletconnect_logger__WEBPACK_IMPORTED_MODULE_3__.pino) is not a function
Describe the bug
A typings error after after initilization universalProvider

SDK Version (if relevant)
"typescript": "^4.7.2",
"@angular/core": "^14.0.0",
"@walletconnect/universal-provider": "^2.1.2",

To Reproduce
To reproduce the behavior follow this:
`    const provider = await UniversalProvider.init({
      projectId: '2189389217bSJHDudyaw89dasd',
    });
    `

Create a new application
Install the above packages
Run script

"TypeError: (0 , _walletconnect_logger__WEBPACK_IMPORTED_MODULE_3__.pino) is not a function
    at new l (http://localhost:4200/vendor.js:273046:216)
    at http://localhost:4200/vendor.js:273053:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:4200/vendor.js:608993:24)
    at _next (http://localhost:4200/vendor.js:609015:9)
    at http://localhost:4200/vendor.js:609022:7
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:11900:21)
    at http://localhost:4200/vendor.js:609011:12
    at l.init (http://localhost:4200/vendor.js:273055:7)
    at http://localhost:4200/main.js:7073:105"

### PR DESCRIPTION
**Pull request by bkrem**
# Description

- Import `pino` from its own dep as before until the issue with using the re-exported approach is resolved.
- Followup to fix runtime import issues caused by #1616
- Fixes #1634 

## How Has This Been Tested?

- Tested against example dapp/wallet via canary `2.1.2-eaa4818c`

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by devceline — COMMENTED** [review]
LGTM, but maybe let's stick with a strict version `7.11.0` and not `^7.11.0`, to match all the other packages and maintain a sane lockfile.

**Review by devceline — APPROVED** [review]
LGTM

**Comment by clemente-xyz** [comment]
are this changes already available on a version of WC?

Needing them ASAP :) @bkrem

**Comment by bkrem** [comment]
@ClementeSerrano yup available as `2.1.3`, replied to you here: https://github.com/WalletConnect/walletconnect-monorepo/issues/1612#issuecomment-1313605437
