### PR TITLE
chore: logger update

### PR DESCRIPTION
**Pull request by ganchoradkov**
# Description
Removed explicit `pino` declarations and the dep is now imported via `@walletconnect/logger`
Removed `pino-pretty` as it no longer used

Resolves # ([browse](https://github.com/WalletConnect/walletconnect-monorepo/issues) or [create](https://github.com/WalletConnect/walletconnect-monorepo/issues/new/choose))

## How Has This Been Tested?
npm run test
dogfooding in example apps

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by bkrem — APPROVED** [review]
LGTM 🚀 

So assuming all logging works as before e.g. in the example dapp where debug logging is enabled?

**Comment by ganchoradkov** [comment]
> LGTM rocket
> 
> So assuming all logging works as before e.g. in the example dapp where debug logging is enabled?

Yes! Logging behaviour is the same in browsers & node/console 🚀
image

**Comment by bkrem** [comment]
Perfect, all good from my side 💪

**Comment by bkrem** [comment]
Relates to #1612

**Comment by khoanguyen-yang** [comment]
I got error when upgraded to `2.1.2` on React Native

TypeError: undefined is not a function (near '..._$$_REQUIRE(_dependencyMap[12], "@walletconnect/logger").pino...')

**Comment by sett21** [comment]
`Uncaught TypeError: (0 , _walletconnect_logger__WEBPACK_IMPORTED_MODULE_2__.pino) is not a function `

after update to 2.1.2

**Comment by bkrem** [comment]
Hi @khoanguyen-yang, @sett21,

Thanks for reporting this, this seems seems to be some specific runtime issue with re-exported `pino` that our tests and CI didn't catch. 

We're working on a patch for this for `2.1.3`, in the meantime there's no drawback to staying on `2.1.1` for now 👍 

Issue has been set up here: #1634
