### ISSUE TITLE
TypeError: connector.signPersonalMessage is not a function

### ISSUE THREAD

**Issue by sssemil** [WalletConnect/walletconnect-monorepo#571]
Hi, I'm trying to sign a message, and after executing connect, the following is executed:
```js
const message = "test message";

const hexMsg = convertUtf8ToHex(message);

const msgParams = [hexMsg, accounts[0]];

connector.signPersonalMessage(msgParams).then(
  function (result) {
    console.log("sign result:", result)
  }
)
```

However, the following error occurs:
```
TypeError: connector.signPersonalMessage is not a function. (In 'connector.signPersonalMessage(msgParams)', 'connector.signPersonalMessage' is undefined)
```

This is also the case with some other functions in connector, but connect function appears to be functional (I get accounts, chainId, etc. back).

Any help is much appreciated. Thanks.

**Comment by sssemil** [comment]
Maybe this helps, the connector object print - https://gist.github.com/sssemil/caf62a0556730dbd5323e2c05e5cfb32

**Comment by sssemil** [comment]
Works fine on v1.4.1, but not on v1.5.2.

**Comment by carlosdp** [comment]
It seems the `connector` object only has the `connect` function and is missing every other function. This is on 1.5.3

<img width="1079" alt="Screen Shot 2021-08-09 at 11 37 30 AM" src="https://user-images.githubusercontent.com/198739/128748527-a9643d3b-c1aa-4a76-9936-4add77fb3764.png">

**Comment by carlosdp** [comment]
Made a fix PR here: https://github.com/WalletConnect/walletconnect-monorepo/pull/575

**Comment by Maxusz666** [comment]
Ok

**Comment by carlosdp** [comment]
I published this branch to `@carlosdp/react-native-dapp` in the mean time, for anyone who needs it.

**Comment by dsemenovsky** [comment]
Hey guys, I ask you to fix this ASAP, please. It was really frustrating for the last couple of days trying to set it up.

**Comment by finessevanes** [comment]
@dsemenovsky are you still having this issue?
