### ISSUE TITLE
(0 , _walletconnect_logger__WEBPACK_IMPORTED_MODULE_3__.pino) is not a function

### ISSUE THREAD

**Issue by OstapDutkevych** [WalletConnect/walletconnect-monorepo#1634]
Describe the bug
A typings error after after initilization universalProvider

SDK Version (if relevant)
"typescript": "^4.7.2",
"@angular/core": "^14.0.0",
"@walletconnect/universal-provider": "^2.1.2",

To Reproduce
To reproduce the behavior follow this:
`    const provider = await UniversalProvider.init({
      projectId: '2189389217bSJHDudyaw89dasd',
    });
    `

Create a new application
Install the above packages
Run script

"TypeError: (0 , _walletconnect_logger__WEBPACK_IMPORTED_MODULE_3__.pino) is not a function
    at new l (http://localhost:4200/vendor.js:273046:216)
    at http://localhost:4200/vendor.js:273053:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:4200/vendor.js:608993:24)
    at _next (http://localhost:4200/vendor.js:609015:9)
    at http://localhost:4200/vendor.js:609022:7
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:11900:21)
    at http://localhost:4200/vendor.js:609011:12
    at l.init (http://localhost:4200/vendor.js:273055:7)
    at http://localhost:4200/main.js:7073:105"

**Comment by bkrem** [comment]
Hi @OstapDutkevych,

Thanks for reporting this, this seems to be some specific runtime issue with re-exported `pino` that our tests and CI didn't catch. 

We're working on a patch for this for `2.1.3`, in the meantime there's no drawback to staying on `2.1.1` for now until this is patched.

**Comment by bkrem** [comment]
This should now be patched in `2.1.3`/`@latest`: https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.3

Please let us know if you are still able to reproduce the issue.

cc @khoanguyen-yang, @sett21

**Comment by bkrem** [comment]
@ganchoradkov leaving this open since we should either a) find root cause and then use the re-exported pino internally as we were planning or b) remove the re-export if unreliable and then keep the explicit pino dep as it is now

**Comment by ZeeshanAhmadKhalil** [comment]
Getting this error as well
Should i switch to V1?

**Comment by bkrem** [comment]
@ZeeshanAhmadKhalil fixed in `2.1.3`, see above

**Comment by ZeeshanAhmadKhalil** [comment]
Working fine in `2.1.3` thank you

**Comment by sett21** [comment]
Thanks! All working fine!

пн, 14 нояб. 2022 г. в 15:20, Zeeshan Ahmad Khalil ***@***.***

**Comment by antonio-ivanovski** [comment]
Thanks for the fast response. It is fixed 👍

**Comment by ganchoradkov** [comment]
closing as the the bug was hotfixed + merged PR properly resolving the issue https://github.com/WalletConnect/walletconnect-utils/pull/37
